name: ðŸ› Bug Report
description: Report a bug or issue with the CIP8 Verifier library
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the following information to help us understand and reproduce the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting a bug report
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have read the [README.md](https://github.com/cardano-php/cip8-verifier/blob/main/README.md) documentation
          required: true
        - label: I am using a supported PHP version (8.1+)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Create a VerificationRequest with...
        2. Call verifier->verify()...
        3. Expected result vs actual result...
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code sample that reproduces the issue
      placeholder: |
        ```php
        <?php
        use CardanoPhp\CIP8Verifier\CIP8Verifier;
        use CardanoPhp\CIP8Verifier\DTO\VerificationRequest;
        
        // Your code here...
        ```
      render: php

  - type: textarea
    id: error
    attributes:
      label: Error Messages/Stack Trace
      description: Any error messages, exceptions, or stack traces
      placeholder: Paste error messages here...
      render: text

  - type: dropdown
    id: php_version
    attributes:
      label: PHP Version
      description: What version of PHP are you using?
      options:
        - PHP 8.1
        - PHP 8.2
        - PHP 8.3
        - PHP 8.4
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: library_version
    attributes:
      label: CIP8 Verifier Version
      description: What version of the library are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: operating_system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Docker
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: wallet_type
    attributes:
      label: Wallet Type (if applicable)
      description: What type of Cardano wallet are you testing with?
      options:
        - Not applicable
        - Lite wallet (Nami, Eternl, etc.)
        - Hardware wallet (Ledger)
        - Custom implementation
        - Unknown

  - type: dropdown
    id: network
    attributes:
      label: Cardano Network
      description: Which Cardano network are you testing on?
      options:
        - Testnet (networkMode = 0)
        - Mainnet (networkMode = 1)
        - Both
        - Not applicable

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem, environment details, or related information
      placeholder: Add any other context about the problem here...

  - type: checkboxes
    id: security
    attributes:
      label: Security Consideration
      description: Please confirm this is not a security issue
      options:
        - label: This bug report does NOT contain sensitive information or security vulnerabilities
          required: true